### ISSUE TITLE
Two tests failing to be corrected

### ISSUE THREAD

**Issue by gusmith** [data61/blocklib#15]
On `master` and `feature-azure-pipelines` branches, the tests `blocklib.signature_generator.generate_by_soundex` and  `test_generate_signatures` are consistently failing running pytest.

**Comment by gusmith** [comment]
The logs are :
```
blocklib/signature_generator.py ...F                                     [ 16%]
tests/test_blocks_generators.py ...                                      [ 29%]
tests/test_candidate_block_generator.py ..                               [ 37%]
tests/test_get_config.py ..                                              [ 45%]
tests/test_pprlindex.py ..                                               [ 54%]
tests/test_pprllambdafold.py ...                                         [ 66%]
tests/test_pprlpsig.py ..                                                [ 75%]
tests/test_signature_generator.py ..F.                                   [ 91%]
tests/test_validation.py ..                                              [100%]

=================================== FAILURES ===================================
__________ [doctest] blocklib.signature_generator.generate_by_soundex __________
071 Generate a phonetic encoding of features using soundex.
072 
073     >>> sigs = generate_by_soundex(1, ('Joyce', 'Wang', 2134))
UNEXPECTED EXCEPTION: UnicodeDecodeError('ascii', b'@\x8f\x08\xbe\xacU', 1, 2, 'ordinal not in range(128)')
Traceback (most recent call last):

  File "/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/doctest.py", line 1330, in __run
    compileflags, 1), test.globs)

  File "<doctest blocklib.signature_generator.generate_by_soundex[0]>", line 1, in <module>

  File "/home/vsts/work/1/s/blocklib/signature_generator.py", line 79, in generate_by_soundex
    return soundex(feature)

  File "src/fuzzy.pyx", line 230, in fuzzy.Soundex.__call__

UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 1: ordinal not in range(128)

/home/vsts/work/1/s/blocklib/signature_generator.py:73: UnexpectedException
______________________ TestPSig.test_generate_signatures _______________________

self = <test_signature_generator.TestPSig testMethod=test_generate_signatures>

    def test_generate_signatures(self):
        """Test a multi-stragegy signatures."""
        dtuple = ('Joyce', 'Wang', 2134)
        signatures = [
            [
                {'type': 'feature-value', 'feature_idx': 0},
                {'type': 'feature-value', 'feature_idx': 1},
            ],
            [
                {'type': 'soundex', 'feature_idx': 0},
                {'type': 'soundex', 'feature_idx': 1},
            ]
        ]
        signatures = generate_signatures(signatures, dtuple)
>       assert signatures == {"J2W52", "JoyceWang"}
E       AssertionError: assert {'', 'JoyceWang'} == {'J2W52', 'JoyceWang'}
E         Extra items in the left set:
E         ''
E         Extra items in the right set:
E         'J2W52'
E         Use -v to get the full diff
```

**Comment by gusmith** [comment]
This issue is not yet closed (at least it was not fixed in master). It is supposed to come with the branch #13 were some functionality and the corresponding tests will be removed.
